# Cloud Build configuration for automatic deployment
# Triggered on push to main branch

steps:
  # ==================== BACKEND ====================
  # Build Backend Docker Image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/backend:$COMMIT_SHA"
      - "-t"
      - "gcr.io/$PROJECT_ID/backend:latest"
      - "./backend"
    id: "build-backend"

  # Push Backend Image with Commit SHA
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/backend:$COMMIT_SHA"]
    id: "push-backend-sha"
    waitFor: ["build-backend"]

  # Push Backend Image with Latest Tag
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/backend:latest"]
    id: "push-backend-latest"
    waitFor: ["build-backend"]

  # Deploy Backend to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "backend"
      - "--image=gcr.io/$PROJECT_ID/backend:$COMMIT_SHA"
      - "--region=us-central1"
      - "--platform=managed"
      - "--allow-unauthenticated"
    id: "deploy-backend"
    waitFor: ["push-backend-sha"]

  # ==================== FRONTEND ====================
  # Build Frontend
  - name: "node:18"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        cd frontend
        echo "Installing dependencies..."
        npm ci
        echo "Building production bundle..."
        npm run build
        echo "Build complete!"
    id: "build-frontend"

  # Deploy Frontend to Cloud Storage
  - name: "gcr.io/cloud-builders/gsutil"
    args:
      - "-m"
      - "rsync"
      - "-r"
      - "-d"
      - "-c" # Compare checksums instead of mtime
      - "frontend/dist"
      - "gs://${_BUCKET_NAME}"
    id: "deploy-frontend"
    waitFor: ["build-frontend"]

  # Set Cache Headers for Assets (JS, CSS, Images)
  - name: "gcr.io/cloud-builders/gsutil"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gsutil -m setmeta -h "Cache-Control:public, max-age=31536000, immutable" \
          "gs://${_BUCKET_NAME}/assets/**/*.js" || true
        gsutil -m setmeta -h "Cache-Control:public, max-age=31536000, immutable" \
          "gs://${_BUCKET_NAME}/assets/**/*.css" || true
        gsutil -m setmeta -h "Cache-Control:public, max-age=31536000, immutable" \
          "gs://${_BUCKET_NAME}/assets/**/*.png" || true
        gsutil -m setmeta -h "Cache-Control:public, max-age=31536000, immutable" \
          "gs://${_BUCKET_NAME}/assets/**/*.jpg" || true
        gsutil -m setmeta -h "Cache-Control:public, max-age=31536000, immutable" \
          "gs://${_BUCKET_NAME}/assets/**/*.svg" || true
    id: "cache-assets"
    waitFor: ["deploy-frontend"]

  # Set Cache Headers for HTML (shorter cache)
  - name: "gcr.io/cloud-builders/gsutil"
    args:
      - "-m"
      - "setmeta"
      - "-h"
      - "Cache-Control:public, max-age=3600"
      - "gs://${_BUCKET_NAME}/*.html"
    id: "cache-html"
    waitFor: ["deploy-frontend"]

  # Invalidate Cloud CDN Cache (if using CDN)
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [ -n "${_CDN_ENABLED}" ]; then
          gcloud compute url-maps invalidate-cdn-cache ${_URL_MAP_NAME} \
            --path "/*" \
            --async || echo "CDN cache invalidation skipped"
        else
          echo "CDN not enabled, skipping cache invalidation"
        fi
    id: "invalidate-cdn"
    waitFor: ["deploy-frontend"]

# Images to be pushed to Container Registry
images:
  - "gcr.io/$PROJECT_ID/backend:$COMMIT_SHA"
  - "gcr.io/$PROJECT_ID/backend:latest"

# Substitution variables (can be overridden in trigger settings)
substitutions:
  _BUCKET_NAME: "event-tickets-frontend-prod"
  _URL_MAP_NAME: "event-tickets-lb"
  _CDN_ENABLED: "true"

# Build options
options:
  # Use faster machine type for builds
  machineType: "E2_HIGHCPU_8"

  # Only log to Cloud Logging (not legacy logs)
  logging: CLOUD_LOGGING_ONLY

  # Increase disk size if needed
  diskSizeGb: 100

  # Dynamic substitution variables
  substitution_option: "ALLOW_LOOSE"

# Overall timeout for the build
timeout: "1200s"
